
title: İşte Pay
description: >- # this means to ignore newlines until "baseurl:"
  Ödeme Kuruluşu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://istepay.com" # the base hostname & protocol for your site, e.g. http://example.com
host: 0.0.0.0
# port: 4000

nav:
  - text: Başvuru
    link: /apply/
  - text: Hakkımızda
    link: /about/
  - text: Ücretler
    link: /fees/
  - text: Duyurular
    link: /announcements/
  - text: İletişim
    link: /contact/


footer_cta: Size Nasıl Yardımcı Olabiliriz?
footer_cta_link: mailto:iletisim@istepay.com
footer_cta2: Öneri ve itiraz formunu buradan indirebilirsiniz.
footer_cta2_link: /oneri-ve-itiraz-formu.docx
footer_content_1: İşte Pay Ödeme Kuruluşu A.Ş.
footer_content_2: "@2021 Tüm Hakları Saklıdır."
footer_content_3: |+
  +90 (212) 285 01 22
  info@istepay.com
  Reşitpaşa Mah. Katar Cad.
  Arı Teknokent 3 Binası No:<span> 4  
  İç Kapı No:<span> 402/B
  Sarıyer/İstanbul
footer_navigation_1_title: Güvenlik
footer_navigation_1:
    - text: Gizlilik Politikası
      link: /privacy/
    - text: KVKK
      link: /kvkk/
    - text: Güvenlik
      link: /security/
    - text: Yasal Uyarılar
      link: /legal/
footer_navigation_2_title: Hakkında
footer_navigation_2:
    - text: Hakkımızda
      link: /about/
    - text: Sıkça Sorulan Sorular
      link: /sss/
    - text: Ücretler
      link: /fees/
    - text: İletişim
      link: /contact/

collections:
  projects:
    output: true


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


include: [".well-known"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
